IPFS ?= ipfs
MA ?= ma
OUT ?= dist/lambda-ma.yaml
CID_DIR ?= dist/cids

SCHEME_ACTOR_CID ?= bafkreicpvj2akfbtry4d2qgxpu5n7uhftosyod5dxuumkj2nfvmawtjwu4
SCHEME_STDLIB_CID ?= bafkreialwzyindzb53xgwchpnb5f6cuatrixbdmsbr3gkdykanbilq6ecy

ACTORS := root avatar room exit duck
CID_FILES := $(ACTORS:%=$(CID_DIR)/%.cid)

.PHONY: all publish root-cid bootstrap check clean show-cids

all: $(OUT)

publish: $(CID_FILES)

$(CID_DIR):
	mkdir -p "$@"

$(CID_DIR)/%.cid: actors/%.ma | $(CID_DIR)
	$(IPFS) add --quieter "$<" > "$@"

$(OUT): lambda-ma.template.yaml Makefile $(CID_FILES)
	mkdir -p "$(@D)"
	root_cid=$$(cat "$(CID_DIR)/root.cid"); \
	avatar_cid=$$(cat "$(CID_DIR)/avatar.cid"); \
	room_cid=$$(cat "$(CID_DIR)/room.cid"); \
	exit_cid=$$(cat "$(CID_DIR)/exit.cid"); \
	duck_cid=$$(cat "$(CID_DIR)/duck.cid"); \
	sed \
	  -e '1s|.*|# Generated λ-間 bootstrap.|' \
	  -e '2s|.*|# Do not edit this file by hand; edit lambda-ma.template.yaml,|' \
	  -e '3s|.*|# Makefile, or actors/*.ma, then run `make`.|' \
	  -e "s|__SCHEME_ACTOR_CID__|$(SCHEME_ACTOR_CID)|g" \
	  -e "s|__SCHEME_STDLIB_CID__|$(SCHEME_STDLIB_CID)|g" \
	  -e "s|__ROOT_BEHAVIOUR_CID__|$$root_cid|g" \
	  -e "s|__AVATAR_BEHAVIOUR_CID__|$$avatar_cid|g" \
	  -e "s|__ROOM_BEHAVIOUR_CID__|$$room_cid|g" \
	  -e "s|__EXIT_BEHAVIOUR_CID__|$$exit_cid|g" \
	  -e "s|__DUCK_BEHAVIOUR_CID__|$$duck_cid|g" \
	  "$<" > "$@"

root-cid: $(OUT)
	$(MA) --gen-root-cid "$(OUT)"

bootstrap: root-cid

check: $(OUT)
	@test -z "$$(grep -n '__[A-Z_]*__' "$(OUT)" || true)"

show-cids: $(CID_FILES)
	@for name in $(ACTORS); do printf '%-8s %s\n' "$$name" "$$(cat "$(CID_DIR)/$$name.cid")"; done

clean:
	rm -rf dist
