IPFS ?= ipfs
MA ?= ma
OUT ?= dist/lambda-ma.yaml
CID_DIR ?= dist/cids

SCHEME_ACTOR_DIR ?= scheme-actor
SCHEME_ACTOR_WASM := $(SCHEME_ACTOR_DIR)/actor.wasm
SCHEME_STDLIB := $(SCHEME_ACTOR_DIR)/stdlib.ma
SCHEME_ACTOR_CID_FILE := $(CID_DIR)/scheme-actor.cid
SCHEME_STDLIB_CID_FILE := $(CID_DIR)/scheme-stdlib.cid

ACTORS := root avatar room exit agent rms duck thing
CID_FILES := $(ACTORS:%=$(CID_DIR)/%.cid)

.PHONY: all publish root-cid bootstrap check clean show-cids FORCE

all: $(OUT)

publish: $(SCHEME_ACTOR_CID_FILE) $(SCHEME_STDLIB_CID_FILE) $(CID_FILES)

$(CID_DIR):
	mkdir -p "$@"

$(SCHEME_ACTOR_WASM): FORCE
	$(MAKE) -C "$(SCHEME_ACTOR_DIR)" actor.wasm

$(SCHEME_ACTOR_CID_FILE): $(SCHEME_ACTOR_WASM) | $(CID_DIR)
	$(IPFS) add --quieter "$<" > "$@"

$(SCHEME_STDLIB_CID_FILE): $(SCHEME_STDLIB) | $(CID_DIR)
	$(IPFS) add --quieter "$<" > "$@"

$(CID_DIR)/%.cid: actors/%.ma | $(CID_DIR)
	$(IPFS) add --quieter "$<" > "$@"

$(OUT): lambda-ma.template.yaml Makefile $(SCHEME_ACTOR_CID_FILE) $(SCHEME_STDLIB_CID_FILE) $(CID_FILES)
	mkdir -p "$(@D)"
	scheme_actor_cid=$$(cat "$(SCHEME_ACTOR_CID_FILE)"); \
	scheme_stdlib_cid=$$(cat "$(SCHEME_STDLIB_CID_FILE)"); \
	root_cid=$$(cat "$(CID_DIR)/root.cid"); \
	avatar_cid=$$(cat "$(CID_DIR)/avatar.cid"); \
	room_cid=$$(cat "$(CID_DIR)/room.cid"); \
	exit_cid=$$(cat "$(CID_DIR)/exit.cid"); \
	agent_cid=$$(cat "$(CID_DIR)/agent.cid"); \
	rms_cid=$$(cat "$(CID_DIR)/rms.cid"); \
	duck_cid=$$(cat "$(CID_DIR)/duck.cid"); \
	thing_cid=$$(cat "$(CID_DIR)/thing.cid"); \
	sed \
	  -e '1s|.*|# Generated λ-間 bootstrap.|' \
	  -e '2s|.*|# Do not edit this file by hand; edit lambda-ma.template.yaml,|' \
	  -e '3s|.*|# Makefile, or actors/*.ma, then run `make`.|' \
	  -e "s|__SCHEME_ACTOR_CID__|$$scheme_actor_cid|g" \
	  -e "s|__SCHEME_STDLIB_CID__|$$scheme_stdlib_cid|g" \
	  -e "s|__ROOT_BEHAVIOUR_CID__|$$root_cid|g" \
	  -e "s|__AVATAR_BEHAVIOUR_CID__|$$avatar_cid|g" \
	  -e "s|__ROOM_BEHAVIOUR_CID__|$$room_cid|g" \
	  -e "s|__EXIT_BEHAVIOUR_CID__|$$exit_cid|g" \
	  -e "s|__AGENT_BEHAVIOUR_CID__|$$agent_cid|g" \
	  -e "s|__RMS_BEHAVIOUR_CID__|$$rms_cid|g" \
	  -e "s|__DUCK_BEHAVIOUR_CID__|$$duck_cid|g" \
	  -e "s|__THING_BEHAVIOUR_CID__|$$thing_cid|g" \
	  "$<" > "$@"

root-cid: $(OUT)
	$(MA) --gen-root-cid "$(OUT)"

bootstrap: root-cid

check: $(OUT)
	@test -z "$$(grep -n '__[A-Z_]*__' "$(OUT)" || true)"

show-cids: $(SCHEME_ACTOR_CID_FILE) $(SCHEME_STDLIB_CID_FILE) $(CID_FILES)
	@printf '%-14s %s\n' "scheme-actor" "$$(cat "$(SCHEME_ACTOR_CID_FILE)")"
	@printf '%-14s %s\n' "scheme-stdlib" "$$(cat "$(SCHEME_STDLIB_CID_FILE)")"
	@for name in $(ACTORS); do printf '%-8s %s\n' "$$name" "$$(cat "$(CID_DIR)/$$name.cid")"; done

clean:
	rm -rf dist
	$(MAKE) -C "$(SCHEME_ACTOR_DIR)" clean

FORCE:
